In [14]:
import tensorflow as tf
from tensorflow import keras
tf.__version__

'2.2.0'

https://www.w3cschool.cn/tensorflow_python/tf_nn_conv2d.html

In [4]:
#[batch,in_height,in_width,in_channels]  输入图片
x = tf.random.normal([1,5,5,3])
x

<tf.Tensor: shape=(1, 5, 5, 3), dtype=float32, numpy=
array([[[[-1.0796763 ,  0.16407676, -0.43644246],
         [-0.59060365,  0.5237709 ,  0.66209453],
         [-1.2255495 ,  0.07583319, -0.7999639 ],
         [ 0.7179515 , -0.32323232,  1.1237652 ],
         [-1.0006275 , -1.8259741 ,  1.440705  ]],

        [[-0.24039356,  0.48894772,  0.21000075],
         [-1.900483  ,  0.6019853 , -1.1994984 ],
         [-0.31018028, -1.04581   ,  0.44087824],
         [ 1.1875182 ,  1.1882782 ,  1.4094836 ],
         [ 0.14373669,  0.4887192 , -1.0168269 ]],

        [[-0.9035847 , -0.22504053, -0.8837197 ],
         [-0.5466531 ,  0.8516749 ,  0.29149094],
         [-1.6240342 ,  0.05333041,  0.12097648],
         [ 0.9129341 , -1.260442  ,  0.735932  ],
         [-1.6928698 ,  0.60141504, -1.0198783 ]],

        [[ 0.06180894,  2.7327628 , -0.45489228],
         [ 0.39767295,  1.3011853 ,  1.2788086 ],
         [ 1.0440459 ,  2.209207  , -0.3826997 ],
         [ 1.062116  , -0.10848645, -1.3

In [ ]:
# [filter_height, filter_width, in_channels, out_channels]的滤波器

In [7]:
w = tf.random.normal([3,3,3,6])

In [ ]:
# padding [[0, 0], [pad_top,pad_bottom], [pad_left, pad_right], [0, 0]]

In [8]:
out1 = tf.nn.conv2d(input=x, 
                    filters=w, 
                    strides=[1,1,1,1],
                    padding=[[0, 0], [0, 0], [0, 0],[0, 0]])
out1

<tf.Tensor: shape=(1, 3, 3, 6), dtype=float32, numpy=
array([[[[ 2.1259990e+00, -1.0735003e+00, -4.1122146e+00,
           8.2717329e-01, -5.2947521e+00,  1.1743492e+00],
         [ 6.5657187e+00, -2.3069324e+00,  2.3569706e-01,
           7.5953001e-01,  3.5538132e+00, -3.0379040e+00],
         [-3.5656123e+00,  5.6525922e+00, -2.2932315e-01,
           5.9167469e-01, -1.2391582e+01, -1.0450058e+00]],

        [[-1.4284374e+00, -5.6155629e+00, -5.7605305e+00,
          -2.4027624e+00,  1.5231390e+00, -3.8803356e+00],
         [-1.2106009e+01, -1.0323821e+01, -3.5976679e+00,
          -1.2430691e+01,  1.6851904e+00,  4.0572209e+00],
         [-1.4741735e+01,  3.0359144e+00,  1.4227915e+01,
          -3.7830262e+00,  1.8532524e+00, -3.7894959e+00]],

        [[ 2.1316350e+00,  7.4641790e+00,  2.1328695e+00,
           1.3843673e-02,  1.3900663e+00,  5.5779152e+00],
         [-2.8995848e+00, -4.4945812e+00, -2.4189606e+00,
          -2.2466463e-01,  3.0717752e+00,  3.3662701e+00],
      

In [10]:
out2 = tf.nn.conv2d(input=x, 
                    filters=w, 
                    strides=1,
                    padding=[[0, 0], [0, 0], [0, 0],[0, 0]])
out2

<tf.Tensor: shape=(1, 3, 3, 6), dtype=float32, numpy=
array([[[[ 2.1259990e+00, -1.0735003e+00, -4.1122146e+00,
           8.2717329e-01, -5.2947521e+00,  1.1743492e+00],
         [ 6.5657187e+00, -2.3069324e+00,  2.3569706e-01,
           7.5953001e-01,  3.5538132e+00, -3.0379040e+00],
         [-3.5656123e+00,  5.6525922e+00, -2.2932315e-01,
           5.9167469e-01, -1.2391582e+01, -1.0450058e+00]],

        [[-1.4284374e+00, -5.6155629e+00, -5.7605305e+00,
          -2.4027624e+00,  1.5231390e+00, -3.8803356e+00],
         [-1.2106009e+01, -1.0323821e+01, -3.5976679e+00,
          -1.2430691e+01,  1.6851904e+00,  4.0572209e+00],
         [-1.4741735e+01,  3.0359144e+00,  1.4227915e+01,
          -3.7830262e+00,  1.8532524e+00, -3.7894959e+00]],

        [[ 2.1316350e+00,  7.4641790e+00,  2.1328695e+00,
           1.3843673e-02,  1.3900663e+00,  5.5779152e+00],
         [-2.8995848e+00, -4.4945812e+00, -2.4189606e+00,
          -2.2466463e-01,  3.0717752e+00,  3.3662701e+00],
      

In [13]:
out3 = tf.nn.conv2d(input=x, 
                    filters=w, 
                    strides=[1,1,1,1],
                    padding='SAME') #same就是自动补零 四周补零 输出图像大小不变
out3

<tf.Tensor: shape=(1, 5, 5, 6), dtype=float32, numpy=
array([[[[-4.0740013e-01, -1.3627769e+00, -8.8546926e-01,
          -7.8113723e-01, -1.4312645e+00, -1.8456262e+00],
         [ 9.8815882e-01, -3.6563964e+00,  5.4939728e+00,
           1.6255629e+00,  9.9751991e-01, -1.7843958e+00],
         [ 2.0149882e+00, -2.1347544e+00, -1.6638799e-01,
           5.2511373e+00, -1.9015654e+00, -1.5005975e+00],
         [ 5.2406297e+00,  4.0283871e+00, -9.1768684e+00,
          -2.1708179e+00, -5.2883878e+00, -2.8375945e+00],
         [-8.8734465e+00, -6.3234634e+00,  3.9304748e+00,
          -7.2814631e+00,  2.7658014e+00,  1.5661064e+00]],

        [[-2.2502925e+00, -1.8965503e+00,  2.6798611e+00,
          -3.4565008e-01,  2.0934875e-01, -2.9343827e+00],
         [ 2.1259990e+00, -1.0735003e+00, -4.1122146e+00,
           8.2717329e-01, -5.2947521e+00,  1.1743492e+00],
         [ 6.5657187e+00, -2.3069324e+00,  2.3569706e-01,
           7.5953001e-01,  3.5538132e+00, -3.0379040e+00],
        

In [31]:
cnnlayer = tf.keras.layers.Conv2D(
    filters=4, kernel_size=3)

In [33]:
x


<tf.Tensor: shape=(1, 5, 5, 3), dtype=float32, numpy=
array([[[[-1.0796763 ,  0.16407676, -0.43644246],
         [-0.59060365,  0.5237709 ,  0.66209453],
         [-1.2255495 ,  0.07583319, -0.7999639 ],
         [ 0.7179515 , -0.32323232,  1.1237652 ],
         [-1.0006275 , -1.8259741 ,  1.440705  ]],

        [[-0.24039356,  0.48894772,  0.21000075],
         [-1.900483  ,  0.6019853 , -1.1994984 ],
         [-0.31018028, -1.04581   ,  0.44087824],
         [ 1.1875182 ,  1.1882782 ,  1.4094836 ],
         [ 0.14373669,  0.4887192 , -1.0168269 ]],

        [[-0.9035847 , -0.22504053, -0.8837197 ],
         [-0.5466531 ,  0.8516749 ,  0.29149094],
         [-1.6240342 ,  0.05333041,  0.12097648],
         [ 0.9129341 , -1.260442  ,  0.735932  ],
         [-1.6928698 ,  0.60141504, -1.0198783 ]],

        [[ 0.06180894,  2.7327628 , -0.45489228],
         [ 0.39767295,  1.3011853 ,  1.2788086 ],
         [ 1.0440459 ,  2.209207  , -0.3826997 ],
         [ 1.062116  , -0.10848645, -1.3

In [37]:
out = cnnlayer(x)
out

<tf.Tensor: shape=(1, 3, 3, 4), dtype=float32, numpy=
array([[[[ 1.616219  , -0.11552887, -0.5720947 , -0.67128646],
         [ 0.68914086,  0.0258076 , -0.24555011, -1.035992  ],
         [-1.1087335 ,  1.1843077 , -1.134094  , -0.5227728 ]],

        [[ 1.0003865 ,  0.5550913 , -1.1763178 , -1.4004458 ],
         [ 1.9231681 ,  1.1240331 , -0.22951786, -0.85087585],
         [ 0.4895308 , -2.275455  ,  0.5325477 ,  1.6398743 ]],

        [[-0.99964666, -0.40919372,  0.28919765, -0.4824524 ],
         [-1.0628592 ,  1.6557866 ,  0.7687165 , -0.35519218],
         [-0.44119096, -0.14994344, -0.2611465 ,  1.0477451 ]]]],
      dtype=float32)>

In [38]:
cnnlayer.trainable_variables

[<tf.Variable 'conv2d_2/kernel:0' shape=(3, 3, 3, 4) dtype=float32, numpy=
 array([[[[-0.19561216, -0.24849774,  0.23511472,  0.14296108],
          [-0.12816456,  0.25915918, -0.2630597 , -0.3066634 ],
          [-0.20708813,  0.0428704 ,  0.15825948, -0.00656149]],
 
         [[-0.08809157, -0.0230194 ,  0.15061206,  0.05412683],
          [ 0.06005931,  0.03892857,  0.27541313, -0.09349062],
          [ 0.12222838, -0.26433134,  0.20115897,  0.22815529]],
 
         [[-0.16313782,  0.02490637,  0.06465402,  0.12407863],
          [ 0.14727369, -0.21412788, -0.0887578 ,  0.2960697 ],
          [ 0.03667635,  0.27270213,  0.05269632, -0.15218256]]],
 
 
        [[[-0.306225  ,  0.30431673,  0.0925681 ,  0.21811953],
          [-0.07920258, -0.22854578,  0.05467835,  0.09334221],
          [-0.02201712, -0.25341573,  0.30291703, -0.20183793]],
 
         [[-0.21864313, -0.1394863 , -0.03597695,  0.30148765],
          [-0.15928441,  0.27488634,  0.01936907, -0.1716316 ],
          [-0.