 # P79

In [1]:
import tensorflow.compat.v1 as tf

In [2]:
from numpy.random import RandomState

In [3]:
tf.compat.v1.disable_eager_execution()

In [4]:
batch_size = 8

### 两个输入节点

In [5]:
x = tf.placeholder(tf.float32, shape=(None, 2),name='x-input')

### 回归问题一般只有一个输出节点

In [6]:
y_ = tf.placeholder(tf.float32, shape=(None,1),name='y-input')

### 定义了一个单层的神经网络的前向传播过程,这里就是简单加权和

In [7]:
w1 = tf.Variable(tf.random_normal([2,1],stddev=1,seed=1))

Instructions for updating:
If using Keras pass *_constraint arguments to layers.


In [8]:
y = tf.matmul(x, w1)

### 定义预测多了和预测少了的的成本

In [9]:
loss_less = 10

In [10]:
loss_more = 1

In [11]:
loss = tf.reduce_sum(tf.where(tf.greater(y,y_),
                              (y-y_)*loss_more,
                              (y_-y)*loss_less))

In [12]:
train_step = tf.train.AdamOptimizer(0.001).minimize(loss)

### 通过随机数生成一个模拟数据集

In [13]:
rdm = RandomState(1)

In [14]:
dataset_size = 128

In [15]:
X = rdm.rand(dataset_size,2)

### 设置回归的正确值为两个输入的和加上一个随机量.之所以要加上一个随机量是为了
### 加入不可预测的噪音,否则不同的损失函数意义就不大了,因为不同的损失函数都会在能
### 完全预测正确的时候最低.一般来说噪音为一个均值为0的小量,所以这里噪音设置为-0.05~0.05的随机数

In [16]:
Y = [[x1 + x2 + rdm.rand()/10-0.05] for (x1,x2) in X]

### 训练神经网络

In [17]:
with tf.Session() as sess:
    init_op = tf.global_variables_initializer()
    sess.run(init_op)
    STEP = 5000
    for i in range(STEP):
        start = (i * batch_size) % dataset_size
        end = min(start + batch_size,dataset_size)
        sess.run(train_step,
                 feed_dict={x: X[start:end],y_: Y[start:end]})
        if i%1000==0:
            print(sess.run(w1))
        
#         print(w1.eval())

[[-0.81031823]
 [ 1.4855988 ]]
[[0.01247114]
 [2.138545  ]]
[[0.45567423]
 [2.1706069 ]]
[[0.69968736]
 [1.846531  ]]
[[0.8988668]
 [1.2973604]]
